from typing import Any
import chess
from .base_agent import BaseAgent

class AZLiteAgent(BaseAgent):
    def __init__(self, checkpoint: str | None = None, simulations: int = 64,
                 cpuct: float = 1.0, temperature: float = 1.0, device: str = "cpu") -> None: ...
    @classmethod
    def from_config(cls, cfg: Any) -> "AZLiteAgent": ...
    def select_move(self, board: chess.Board) -> chess.Move: ...
    def update(self, batch: Any) -> dict[str, float]: ...
    def load(self, path: str) -> None: ...
    def save(self, path: str) -> None: ...
    def eval_mode(self) -> None: ...
    def train_mode(self) -> None: ...
