from typing import Any
import chess

class BaseAgent:
    def select_move(self, board: chess.Board) -> chess.Move: ...
    def update(self, *args, **kwargs) -> None: ...
    def load(self, path: str) -> None: ...
    def save(self, path: str) -> None: ...
    def eval_mode(self) -> None: ...
    def train_mode(self) -> None: ...