from typing import Any
import chess
from .base_agent import BaseAgent

class PPOAgent(BaseAgent):
    def __init__(self, checkpoint: str | None = None, device: str = "cpu",
                 clip_ratio: float = 0.2) -> None: ...
    @classmethod
    def from_config(cls, cfg: Any) -> "PPOAgent": ...
    def select_move(self, board: chess.Board) -> chess.Move: ...
    def update(self, rollouts: Any) -> dict[str, float]: ...
    def load(self, path: str) -> None: ...
    def save(self, path: str) -> None: ...
    def eval_mode(self) -> None: ...
    def train_mode(self) -> None: ...
